// Base64 encoded SVG placeholder for sbFT images
export const sbFTPlaceholder = 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1MDAiIGhlaWdodD0iNTAwIiB2aWV3Qm94PSIwIDAgNTAwIDUwMCI+CiAgPHJlY3Qgd2lkdGg9IjUwMCIgaGVpZ2h0PSI1MDAiIGZpbGw9IiMxYjFjMzEiLz4KICA8cmVjdCB4PSI1MCIgeT0iNTAiIHdpZHRoPSI0MDAiIGhlaWdodD0iNDAwIiByeD0iMjAiIHJ5PSIyMCIgZmlsbD0iIzJhMmQ0MiIgc3Ryb2tlPSIjOGExY2ZmIiBzdHJva2Utd2lkdGg9IjIiLz4KICA8Y2lyY2xlIGN4PSIyNTAiIGN5PSIyMDAiIHI9IjEwMCIgZmlsbD0ibm9uZSIgc3Ryb2tlPSIjOGExY2ZmIiBzdHJva2Utd2lkdGg9IjgiLz4KICA8cGF0aCBkPSJNMjUwLDEwMHYyMDAiIHN0cm9rZT0iIzhhMWNmZiIgc3Ryb2tlLXdpZHRoPSI0Ii8+CiAgPHBhdGggZD0iTTE1MCwyMDAgYzAsNTUuMjUgNDQuNzUsMTAwIDEwMCwxMDAiIHN0cm9rZT0iIzhhMWNmZiIgc3Ryb2tlLXdpZHRoPSI0IiBmaWxsPSJub25lIi8+CiAgPHRleHQgeD0iMjUwIiB5PSIyODAiIGZvbnQtZmFtaWx5PSJBcmlhbCIgZm9udC1zaXplPSI0MCIgZmlsbD0iIzhhMWNmZiIgdGV4dC1hbmNob3I9Im1pZGRsZSI+U0JGVDwvdGV4dD4KPC9zdmc+';

// Utility function to handle image errors
export const handleImageError = (e: React.SyntheticEvent<HTMLImageElement>) => {
  const target = e.target as HTMLImageElement;
  target.src = sbFTPlaceholder;
};
