const STAKING_CONTRACT_ADDRESS = ""

const sbFTMarketplace_CONTRACT_ADDRESS = ""

const BASE_TOKEN_ADDRESS = ""

const MOCKUSDCADDRESS = ""

const FLUIDSTAKE_NFT_ADDRESS = ""

const SBFT_TOKEN_ADDRESS = ""